import Navbar from "./NavBar";
import Footer from "./Footer";
import { Classes } from "@blueprintjs/core";
import Head from "next/head";
import classes from "@/styles/Layout.module.css";
import React from "react";
import { useDarkMode, useIsClient } from "usehooks-ts";

export default function Layout({ children }: { children: React.ReactNode }) {
  const { isDarkMode } = useDarkMode(true);
  const isClient = useIsClient();
  const [rootClasses, setRootClasses] = React.useState<string>(classes.light);

  React.useEffect(() => {
    if (isClient) {
      document.documentElement.setAttribute(
        "data-color-scheme",
        isDarkMode ? "dark" : "light"
      );
      if (isDarkMode) {
        setRootClasses(`${Classes.DARK}`);
      } else {
        setRootClasses(``);
      }
    }
  }, [isDarkMode, isClient]);

  return (
    <div className={rootClasses}>
      <div className={classes.wrapper}>
        <div className={classes.layout}>
          <Head>
            <title>GW2 Library</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar />
          <main className={classes.main}>{children}</main>
          <Footer />
        </div>
      </div>
    </div>
  );
}
